apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: certmanager-lab
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: certmanager-lab
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
