apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sidecar.fullname" . }}
  labels:
    {{- include "sidecar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sidecar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sidecar.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sidecar.fullname" . }}
  labels:
    {{- include "sidecar.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sidecar.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
