apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  namespace: rbac-lab
  labels:
    app: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      # Break: SA must exist before pods can use it
      serviceAccountName: secret-reedr
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.10
