apiVersion: v1
kind: Pod
metadata:
  name: greedy
  namespace: pod-failure-lab
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
