apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-stress
  namespace: pod-failure-lab
  labels:
    app: mem-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem-stress
  template:
    metadata:
      labels:
        app: mem-stress
    spec:
      containers:
      - name: stress
        image: polinux/stress
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
