apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netlab
  namespace: network-troubleshoot-lab
spec:
  ingressClassName: traefik
  rules:
  - host: netlab.k8s.orb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-typo
            port:
              number: 80
